@startjson
{
    "shadowStack": [

        {
            "ptrs": [
                               ["Указатель на объект"],
                               "...",
                               ""
                           ]
        }
        ,
        "...",
        " "
    ],
    "shadowHeap": {
       "ptr":"Указатель на объект",
       "links":[
        [
            "Сдвиг на указатель"
        ],
        "...",
        ""
       ],
       "isUsed": "Флаг о использовании"
    }
}
@endjson